project:
  type: book
  output-dir: _site

book:
  title: "Documentation"
  author: "Assa Yeroslaviz"
  chapters:
    - index.qmd
    - chapters/quick-start.qmd
    - chapters/setup-infrastructure.qmd
    - chapters/git-github.qmd
    - chapters/vm-installation.qmd
    - chapters/deploy-operations.qmd
    - chapters/change-log.qmd


format:
  html:
    link-external-newwindow: true
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
