---
title: "Documentation"
---

**BCFMS-project-management** is a Shiny app for a project management system for the MS core facility.

The MS Core Facility provides services such as ​
- Identification of proteins (in-gel or in-solution)
  - “Protein ID”
  - “Protein Coverage”
- In-depth proteome analysis (with and without fractionation)
​  - “Total Proteome”
- Interaction proteomics by Affinity Purification Mass Spectrometry (AP-MS)	
​​​  - “Interaction proteomics”
- Post-translational modification identification (e.g. phosphorylation, ubiquitination, acetylation or glycosylation). Low stoichiometry modifications can be brought into view by enrichment (e.g. Fe-IMAC for phosphorylation)
  - “PTMomics”
  - “Protein Coverage”
- Crosslinking-MS (XL-MS) to extract protein structure distance information
  - “Crosslinking MS”
- Intact mass of proteins and other biomolecules as well as small molecules 
  - “Intact mass”
- Lipidomics / Metabolomics.

* Assistance with experimental design of the studies (required number of samples and replicates)
* Assistance with the use of NGS open source analysis tools
* Data analysis on a collaborative basis

If you have any further questions, please do not hesitate to [contact us @ omicsdesk](mailto:omicsdesk.biochem.mpg.de)!

# Chapters

- [Quick Start](chapters/quick-start.html)
- [Setup & Infrastructure](chapters/setup-infrastructure.html)
- [Git & GitHub](chapters/git-github.html)
- [Deploy & Operations](chapters/deploy-operations.html)
- [LDAP Authentication](chapters/ldap-authentication.html)
- [SQL Handling](chapters/sql-handling.html)
- [Troubleshooting](chapters/troubleshooting.html)
- [Change Log](chapters/change-log.html)
- [Legacy / Archive](chapters/legacy-archive.html)

## How to render

```bash
quarto render Documentation/
```


This booklet consolidates all operational and technical documentation for the sequencing Shiny app.
